baseURL: https://timfanda35.github.io
disablePathToLower: true
languageCode: en-us
title: Bear Su's blog
copyright: "(c) 2019 Bear Su's blog"

theme: hugo-gentoo-theme

google_analytics: UA-5708312-7

paginate: 10
excerpt_separator: "<!-- more -->"

params:
  description: "Running Bear!!!"
  author: "Bear Su"

taxonomies:
  category: "categories"
  tag: "tags"

menu:
  global:
  - name: "Categories"
    url: "/categories/"
