baseURL: https://timfanda35.github.io
disablePathToLower: true
languageCode: en-us
title: Bear Su's Blog
copyright: "(c) 2021 Bear Su's Blog"

theme: hugo-gentoo-theme-custom

googleAnalytics: UA-5708312-7

paginate: 10

params:
  description: "Running Bear!!!"
  author: "Bear Su"

taxonomies:
  category: "categories"
  tag: "tags"

menu:
  global:
  - name: "Categories"
    url: "/categories/"
  - name: "GitHub"
    url: "https://github.com/timfanda35"
  - name: "Twitter"
    url: "https://twitter.com/Fandayo"
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/bearsu"
